name: Message Deleter

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  delete-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bulk Delete Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          # Reusing the destination channel secret, as requested
          DESTINATION_CHANNEL: ${{ secrets.DESTINATION_CHANNEL }}
        run: python bulkdelete/delete_script.py
        
