name: Telegram Message Forwarder

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  forward-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Telegram Forwarder Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          SOURCE_CHANNEL: ${{ secrets.SOURCE_CHANNEL }}
          DESTINATION_CHANNEL: ${{ secrets.DESTINATION_CHANNEL }}
        run: python forward_script.py
        
